### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aman-singal** [coding-blocks/oneauth#1021]
node version:- v12.16.3
python version: v3.8

> @newrelic/native-metrics@4.1.0 install E:\aman\React\oneauth\node_modules\@newrelic\native-metrics     
> node ./lib/pre-build.js install native_metrics

============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean configure
> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build -j 4 native_metrics
  native_metrics.cpp
  GCBinder.cpp
  LoopChecker.cpp
  RUsageMeter.cpp
  win_delay_load_hook.cc
     Creating library E:\aman\React\oneauth\node_modules\@newrelic\native-metrics\build\Release\native_m 
  etrics.lib and object E:\aman\React\oneauth\node_modules\@newrelic\native-metrics\build\Release\native 
  _metrics.exp
  native_metrics.vcxproj -> E:\aman\React\oneauth\node_modules\@newrelic\native-metrics\build\Release\\n 
  ative_metrics.node
install successful: _newrelic_native_metrics-4_1_0-native_metrics-72-win32-x64

> bcrypt@2.0.1 install E:\aman\React\oneauth\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v2.0.1/bcrypt_lib-v2.0.1-node-v72-win32-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@2.0.1 and node@12.16.3 (node-v72 ABI, unknown) 
(falling back to source compile with node-gyp) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
  win_delay_load_hook.cc
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: '
v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\Re
act\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(2663): note: see declaration of ' 
  v8::Value::ToBoolean' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: ' 
v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman 
\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(2701): note: see declaration of ' 
  v8::Value::BooleanValue' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_implementation_12_inl.h(103): error C2664 
: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local< 
v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate 
 *' to 'v8::Local<v8::Context>' (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\nod 
e_modules\bcrypt\build\bcrypt_lib.vcxproj]
  e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_implementation_12_inl.h(105): note: No  
  constructor could take the source type, or constructor overload resolution was ambiguous (compiling so 
  urce file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_implementation_12_inl.h(337): error C2660 
: 'v8::StringObject::New': function does not take 1 arguments (compiling source file ..\src\bcrypt_node. 
cc) [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(5531): note: see declaration of ' 
  v8::StringObject::New' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_implementation_12_inl.h(337): error C2059 
: syntax error: ')' (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modules\bc 
rypt\build\bcrypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1034): error C2661: 'v8::Value::ToStrin
g': no overloaded function takes 0 arguments (compiling source file ..\src\bcrypt_node.cc) [E:\aman\Reac 
t\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1044): error C2664: 'int v8::String::Wr 
iteUtf8(v8::Isolate *,char *,int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isol 
ate *' (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modules\bcrypt\build\bc 
rypt_lib.vcxproj]
  e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1044): note: Types pointed to are unr 
  elated; conversion requires reinterpret_cast, C-style cast or function-style cast (compiling source fi 
  le ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1818): warning C4996: 'v8::Object::Set' 
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3498): note: see declaration of ' 
  v8::Object::Set' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1824): warning C4996: 'v8::Object::Set'
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3498): note: see declaration of ' 
  v8::Object::Set' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1830): warning C4996: 'v8::Object::Set' 
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3507): note: see declaration of ' 
  v8::Object::Set' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1836): warning C4996: 'v8::Object::Get' 
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3553): note: see declaration of ' 
  v8::Object::Get' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1842): warning C4996: 'v8::Object::Get' 
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3553): note: see declaration of ' 
  v8::Object::Get' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1847): warning C4996: 'v8::Object::Get' 
: was declared deprecated (compiling source file ..\src\bcrypt_node.cc) [E:\aman\React\oneauth\node_modu 
les\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(3557): note: see declaration of ' 
  v8::Object::Get' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_object_wrap.h(24): error C2039: 'IsNearDe 
ath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [E:\aman\React 
\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bcrypt_node.cc)
  e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1859): note: see declaration of 'Nan: 
  :Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_object_wrap.h(67): warning C4996: 'v8::Pe 
rsistentBase<v8::Object>::MarkIndependent': was declared deprecated (compiling source file ..\src\bcrypt 
_node.cc) [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\yash\appdata\local\node-gyp\cache\12.16.3\include\node\v8.h(566): note: see declaration of 'v 
  8::PersistentBase<v8::Object>::MarkIndependent' (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan_object_wrap.h(124): error C2039: 'IsNearD 
eath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [E:\aman\Reac 
t\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bcrypt_node.cc)
  e:\aman\react\oneauth\node_modules\bcrypt\node_modules\nan\nan.h(1859): note: see declaration of 'Nan: 
  :Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bcrypt_node.cc)
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(66): error C2664: 'v8::String::Utf8Value::U 
tf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::String>' to 'con 
st v8::String::Utf8Value &' [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(66): note: Reason: cannot convert from 'v 
  8::Local<v8::String>' to 'const v8::String::Utf8Value'
  e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(66): note: No user-defined-conversion ope 
  rator available that can perform this conversion, or the operator cannot be called
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(121): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(121): error C2789: 'minor_ver': an object o 
f const-qualified type must be initialized [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.v 
cxproj]
  e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(121): note: see declaration of 'minor_ver 
  '
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(150): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(150): error C2789: 'minor_ver': an object o 
f const-qualified type must be initialized [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.v 
cxproj]
  e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(150): note: see declaration of 'minor_ver 
  '
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(212): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(212): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(213): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(213): error C2512: 'Nan::Utf8String::Utf8St
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(231): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(231): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(232): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(232): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(312): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(312): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(313): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(313): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(331): error C2661: 'v8::Value::ToString': n
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(331): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(332): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(332): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(352): error C2661: 'v8::Value::ToString': n 
o overloaded function takes 0 arguments [E:\aman\React\oneauth\node_modules\bcrypt\build\bcrypt_lib.vcxp 
roj]
e:\aman\react\oneauth\node_modules\bcrypt\src\bcrypt_node.cc(352): error C2512: 'Nan::Utf8String::Utf8St 
ring': no appropriate default constructor available [E:\aman\React\oneauth\node_modules\bcrypt\build\bcr 
ypt_lib.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\aman\\React\\oneauth\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=E:\\aman\\React\\oneauth\\node_modules\\bcrypt\\lib\\binding" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd E:\aman\React\oneauth\node_modules\bcrypt
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\aman\React\oneauth\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=E:\aman\React\oneauth\node_modules\bcrypt\lib\binding --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\aman\React\oneauth\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)     
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\aman\\React\\oneauth\\node_modules\\bcrypt\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\aman\React\oneauth\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\aman\React\oneauth\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=E:\aman\React\oneauth\node_modules\bcrypt\lib\binding --napi_version=5 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.       

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yash\AppData\Roaming\npm-cache\_logs\2020-06-06T17_13_03_270Z-debug.log

**Comment by aman-singal** [comment]
I have also installed production windows-build-tools but no luck

**Comment by aman-singal** [comment]
tried but now getting an error:
> oneauth@0.7.9 start:dev E:\aman\React\oneauth
> cross-env ONEAUTH_DEV=localhost npm start


> oneauth@0.7.9 start E:\aman\React\oneauth
> node src/server.js

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:245:13
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '../../secrets'
Require stack:
- E:\aman\React\oneauth\src\controllers\verify_otp.js
- E:\aman\React\oneauth\src\routers\login\otp.js
- E:\aman\React\oneauth\src\routers\login\index.js
- E:\aman\React\oneauth\src\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.wrappedResolveFilename [as _resolveFilename] (E:\aman\React\oneauth\node_modules\newrelic\lib\shimmer.js:465:42)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.wrappedLoad [as _load] (E:\aman\React\oneauth\node_modules\newrelic\lib\shimmer.js:476:24)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\aman\React\oneauth\src\controllers\verify_otp.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.wrappedLoad [as _load] (E:\aman\React\oneauth\node_modules\newrelic\lib\shimmer.js:476:24)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\aman\React\oneauth\src\routers\login\otp.js:8:28)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.wrappedLoad [as _load] (E:\aman\React\oneauth\node_modules\newrelic\lib\shimmer.js:476:24)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\aman\React\oneauth\src\routers\login\index.js:21:60)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.wrappedLoad [as _load] (E:\aman\React\oneauth\node_modules\newrelic\lib\shimmer.js:476:24)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\aman\React\oneauth\src\server.js:23:21)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\aman\\React\\oneauth\\src\\controllers\\verify_otp.js',
    'E:\\aman\\React\\oneauth\\src\\routers\\login\\otp.js',
    'E:\\aman\\React\\oneauth\\src\\routers\\login\\index.js',
    'E:\\aman\\React\\oneauth\\src\\server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oneauth@0.7.9 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oneauth@0.7.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.       

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yash\AppData\Roaming\npm-cache\_logs\2020-06-11T05_33_10_908Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oneauth@0.7.9 start:dev: `cross-env ONEAUTH_DEV=localhost npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oneauth@0.7.9 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.       

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yash\AppData\Roaming\npm-cache\_logs\2020-06-11T05_33_10_973Z-debug.log

**Comment by ArunTeltia** [comment]
you just need to read the readme.md 
there is a secretsample.json
make a secret.json and copy all the content of secretsample.json to it and connect to postgresql and it will work 

try this 
dont close the issue maybe someone find the similarly difficulties

**Comment by aman-singal** [comment]
Thanks its worked

**Comment by ArunTeltia** [comment]
Dont close it maybe someone else can find this beneficial @aman-singal

**Comment by aman-singal** [comment]
@ArunTeltia ok
