### ISSUE TITLE
NPM Install Failure

### ISSUE THREAD

**Issue by mio9** [coding-blocks/oneauth#555]
Honestly have no idea what causing that, but i guess it's something failed to download
```
> @newrelic/native-metrics@2.4.0 install D:\Projects\Web\mio9.sh\oneauth\node_modules\@newrelic\native-metrics
> node ./lib/pre-build.js install native_metrics

> C:\Program Files\nodejs\node.exe C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean configure
Traceback (most recent call last):
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ThisTNTSquid\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "clean" "configure"
gyp ERR! cwd D:\Projects\Web\mio9.sh\oneauth\node_modules\@newrelic\native-metrics
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Error: Failed to execute install: Error: Failed to install module: Error: Failed to execute C:\Program Files\nodejs\node.exe C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean configure: code 1; Error: Failed to download https://download.newrelic.com/nodejs_agent/builds/_newrelic_native_metrics-2_4_0-native_metrics-64-win32-x64.gz: code 404

> bcrypt@1.0.3 install D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.7.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.7.0 (node-v64 ABI) (falling back to source compile with node-gyp)
Traceback (most recent call last):
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
Traceback (most recent call last):
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gypgyp  ERR! configure errorERR!
 configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stackgyp     at ChildProcess.onCpExit (C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
 gypERR!  ERR!stack  Error: `gyp` failed with exit code: 1
stackgyp     at ChildProcess.emit (events.js:182:13)
 gyp ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
     at ChildProcess.onCpExit (C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gypgyp ERR!  SystemERR! Windows_NT 10.0.17134
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ThisTNTSquid\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Projects\\Web\\mio9.sh\\oneauth\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\Projects\\Web\\mio9.sh\\oneauth\\node_modules\\bcrypt\\lib\\binding" "--python=python2.7" "--msvs_version=2017"
gyp gyp ERR!ERR!  cwd D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt
gypSystem ERR!  Windows_NT 10.0.17134
node -v v10.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ThisTNTSquid\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Projects\\Web\\mio9.sh\\oneauth\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\Projects\\Web\\mio9.sh\\oneauth\\node_modules\\bcrypt\\lib\\binding" "--python=python2.7" "--msvs_version=2017"
gyp ERR! cwd D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt\lib\binding --python=python2.7 --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Projects\Web\mio9.sh\oneauth\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\Web\\mio9.sh\\oneauth\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ThisTNTSquid\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\Projects\Web\mio9.sh\oneauth\node_modules\bcrypt\lib\binding --python=python2.7 --msvs_version=2017' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@2.4.0 (node_modules\@newrelic\native-metrics):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@2.4.0 install: `node ./lib/pre-build.js install native_metrics`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by championswimmer** [comment]
I think you will succeed with Node v8. v10 support might need changing some dependencies. Will work on that soon

**Comment by Swayamsvk** [comment]
I am also facing the same error already used node version 8 and 10 still the error persists.Can you please provide me the exact steps?

**Comment by championswimmer** [comment]
You'll need nodejs 10 
Python 2.7 

Both should be installed on your PC and then it'll work.

**Comment by Swayamsvk** [comment]
I am currently having both but everytime it shows this error 
 npm install

> @newrelic/native-metrics@4.1.0 install /media/swayam/A:/BOSS/boss_auth/oneauth/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> /home/swayam/.nvm/versions/node/v10.20.1/bin/node /home/swayam/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
> /home/swayam/.nvm/versions/node/v10.20.1/bin/node /home/swayam/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build -j 2 native_metrics
make: Entering directory '/media/swayam/A:/BOSS/boss_auth/oneauth/node_modules/@newrelic/native-metrics/build'
  CXX(target) Release/obj.target/native_metrics/src/native_metrics.o
  CXX(target) Release/obj.target/native_metrics/src/GCBinder.o
  CXX(target) Release/obj.target/native_metrics/src/LoopChecker.o
  CXX(target) Release/obj.target/native_metrics/src/RUsageMeter.o
  SOLINK_MODULE(target) Release/obj.target/native_metrics.node
  COPY Release/native_metrics.node
make: Leaving directory '/media/swayam/A:/BOSS/boss_auth/oneauth/node_modules/@newrelic/native-metrics/build'
install successful: _newrelic_native_metrics-4_1_0-native_metrics-64-linux-x64

> bcrypt@2.0.1 install /media/swayam/A:/BOSS/boss_auth/oneauth/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'nopt'
Require stack:
- /usr/lib/nodejs/node-pre-gyp/lib/node-pre-gyp.js
- /usr/lib/nodejs/node-pre-gyp/bin/node-pre-gyp
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/nodejs/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/nodejs/node-pre-gyp/lib/node-pre-gyp.js',
    '/usr/lib/nodejs/node-pre-gyp/bin/node-pre-gyp'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/swayam/.npm/_logs/2020-05-17T15_38_13_536Z-debug.log
