### ISSUE TITLE
Not working for localhost : SequelizeConnectionError: password authentication failed for user "oneauth"

### ISSUE THREAD

**Issue by XLAR-8** [coding-blocks/oneauth#638]
Desktop/oneauth$ npm run start:dev

 oneauth@0.6.7 start:dev Desktop/oneauth
 cross-env ONEAUTH_DEV=localhost npm start

> oneauth@0.6.7 start /home/tiktok/Desktop/oneauth
> node src/server.js

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13
{ SequelizeConnectionError: password authentication failed for user "oneauth"
    at connection.connect.err (/home/tiktok/Desktop/oneauth/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:24)
    at Connection.connectingErrorHandler (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/client.js:174:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:126:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
  name: 'SequelizeConnectionError',
  parent: 
   { error: password authentication failed for user "oneauth"
    at Connection.parseE (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:121:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
     name: 'error',
     length: 103,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '328',
     routine: 'auth_failed' },
  original: 
   { error: password authentication failed for user "oneauth"
    at Connection.parseE (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:121:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
     name: 'error',
     length: 103,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '328',
     routine: 'auth_failed' } }
Unhandled rejection SequelizeConnectionError: password authentication failed for user "oneauth"
    at connection.connect.err (/home/tiktok/Desktop/oneauth/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:24)
    at Connection.connectingErrorHandler (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/client.js:174:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/home/tiktok/Desktop/oneauth/node_modules/pg/lib/connection.js:126:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

**Comment by championswimmer** [comment]
you need to setup your local db first.
