### ISSUE TITLE
Need help - Not able to run the project locally

### ISSUE THREAD

**Issue by leelatanniru** [coding-blocks/oneauth#776]
I have followed the steps to run the project locally. After running npm run start:dev
 Iam getting the following error. Can any one please help.

Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (C:\Users\leela\Desktop\OpenSourceProjects\oneAuth\oneauth\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:142:24)
    at Connection.connectingErrorHandler (C:\Users\leela\Desktop\OpenSourceProjects\oneAuth\oneauth\node_modules\pg\lib\client.js:140:14)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at Socket.reportStreamError (C:\Users\leela\Desktop\OpenSourceProjects\oneAuth\oneauth\node_modules\pg\lib\connection.js:71:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by 98lenvi** [comment]
you need to be running mongodb and oauth server, This can be a very good issue to be fixed (i.e. update readme.md)

**Comment by leelatanniru** [comment]
@98lenvi could you please update the Readme.md.

**Comment by leelatanniru** [comment]
Could you please provide me the steps to get the app running locally @98lenvi I would like to work on this project :)

**Comment by leelatanniru** [comment]
@abhishek97 Could you please help.
